"""empty message

Revision ID: 1591594d7147
Revises: be3da3882e98
Create Date: 2024-02-10 12:27:46.972038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1591594d7147'
down_revision: Union[str, None] = 'be3da3882e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trouble', sa.Column('pathfile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trouble', 'pathfile')
    # ### end Alembic commands ###
