"""empty message

Revision ID: d580a4783179
Revises: 1591594d7147
Create Date: 2024-02-10 13:12:36.268483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd580a4783179'
down_revision: Union[str, None] = '1591594d7147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trouble', sa.Column('priority', sa.String(), nullable=False))
    op.alter_column('trouble', 'solved',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False,
               nullable=False,
               server_default="Не решено"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trouble', 'solved',
               existing_type=sa.Enum('in_process', 'solved', 'not_solved', name='troublestate'),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('trouble', 'priority')
    # ### end Alembic commands ###
