"""empty message

Revision ID: 7f4e3fa2ca56
Revises: d580a4783179
Create Date: 2024-02-10 13:51:58.209283

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4e3fa2ca56'
down_revision: Union[str, None] = 'd580a4783179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trouble',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('trouble_id', sa.Integer(), nullable=False),
    sa.Column('relate', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['trouble_id'], ['trouble.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('trouble_user_id_fkey', 'trouble', type_='foreignkey')
    op.drop_column('trouble', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trouble', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('trouble_user_id_fkey', 'trouble', 'user', ['user_id'], ['id'])
    op.drop_table('user_trouble')
    # ### end Alembic commands ###
