"""empty message

Revision ID: 9ba27630d464
Revises: 7f4e3fa2ca56
Create Date: 2024-02-10 14:53:48.085024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9ba27630d464'
down_revision: Union[str, None] = '7f4e3fa2ca56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolver_trouble',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trouble_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trouble_id'], ['trouble.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_trouble')
    op.add_column('trouble', sa.Column('reporter_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_foreign_key(None, 'trouble', 'user', ['reporter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trouble', type_='foreignkey')
    op.drop_column('trouble', 'reporter_id')
    op.create_table('user_trouble',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trouble_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relate', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trouble_id'], ['trouble.id'], name='user_trouble_trouble_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_trouble_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_trouble_pkey')
    )
    op.drop_table('resolver_trouble')
    # ### end Alembic commands ###
