"""empty message

Revision ID: bd597eaf8229
Revises: 9ba27630d464
Create Date: 2024-02-10 15:10:34.264716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bd597eaf8229'
down_revision: Union[str, None] = '9ba27630d464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolver_trouble', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_foreign_key(None, 'resolver_trouble', 'user', ['user_id'], ['id'])
    op.drop_column('resolver_trouble', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolver_trouble', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'resolver_trouble', type_='foreignkey')
    op.drop_column('resolver_trouble', 'user_id')
    # ### end Alembic commands ###
